# Site settings
title: Grindlheim
email: contact@grindlheim.com
baseurl: ""
url: "http://www.grindlheim.com"
progress: 90%

# Build options
future: true

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  blanklines: false
  ignore:
    envs: []

plugins:
  - jekyll-sitemap
  #- jekyll-feed

sass:
  style: compressed
  sourcemap: never

exclude:
  - Gemfile
  - Gemfile.lock
  - vs-code-arbeitsbereich.code-workspace
  - README.md
  - "*.psd"
  - "*.py"
  - "*.afphoto"